CREATE TABLE homework_data (
  id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  gen_values   VARCHAR2(100 byte),
  create_date DATE 
);
commit;
insert into homework_data (gen_values, create_date)  
select  dbms_random.string ('a',100) , SYSDATE -  DBMS_RANDOM.value(1,1000) from dual
connect by level <= 1000000;
commit;
exec DBMS_STATS.GATHER_TABLE_STATS('SWED_HW','HOMEWORK_DATA');
exit;
